# Generated by Django 5.0.2 on 2025-05-05 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('faixa', models.CharField(choices=[('BRANCA', 'Branca'), ('AZUL', 'Azul'), ('ROXA', 'Roxa'), ('MARROM', 'Marrom'), ('PRETA', 'Preta')], max_length=20)),
                ('bolsista', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
            ],
        ),
    ]
