# Generated by Django 5.2 on 2025-05-19 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO', 'Cartão'), ('TRANSFERENCIA', 'Transferência')], max_length=20)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('mensalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.mensalidade')),
            ],
        ),
    ]
